apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 7solution
  namespace: argocd
spec:
  project: default
  destination:
    name: ''
    namespace: app
    server: https://kubernetes.default.svc
  source:
    path: app
    repoURL: https://github.com/viruskizz/job-interview-7solution-devops
    targetRevision: main
  sources: []
  syncPolicy: 
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - CreateNamespace=true