name: ci

on:
  push:
    # branches:
    #   - main
    paths-ignore:
      - 'iac/**'
      - 'argocd/**'
env:
  TAG: "$DOCKERHUB_USERNAME/job-interview-7solution-devops"
  VERSION: "latest"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:app"
          push: true
          tags: $TAG:$VERSION